services:
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis
    networks:
      - app-net
    ports:
      - "6379:6379"
  
  database:
    container_name: database
    restart: unless-stopped
    image: mariadb
    networks:
      - app-net
    ports:
      - "5432:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=app

networks:
  app-net: